Update patch set 2
Patch Set 2:

You might find the Android.mk descriptions from android-support-design and android-support-v7-recyclerview interesting :

https://android.googlesource.com/platform/frameworks/support/+/android-8.1.0_r15/design/Android.mk
https://android.googlesource.com/platform/frameworks/support/+/android-8.1.0_r15/v7/recyclerview/Android.mk

They are identical on AOSP Master and AOSP P-DP1.
AOSP Master & now P-DP1, as well as the current non-Jack build, require explicit linkages.

 > # Here is the final static library that apps can link against.
 > # Applications that use this library must specify
 > #
 > #   LOCAL_STATIC_ANDROID_LIBRARIES := \
 > #       android-support-design \
 > #       android-support-transition \
 > #       android-support-v7-appcompat \
 > #       android-support-v7-recyclerview \
 > #       android-support-v4

Example output of the build failure :

 > Warning: android.support.design.internal.NavigationMenuView: can't find referenced class android.support.v7.widget.RecyclerView$LayoutManager
 > Warning: there were 21 unresolved references to classes or interfaces.
 > Warning: there were 9 unresolved references to program class members.
 > Error: Please correct the above warnings first.

Patch-set: 2